#!/bin/sh -eux

# t4ht expects to be un /usr/share/texmf/bin/t4ht (FS#27251)
sed -i s/SELFAUTOPARENT/TEXMFROOT/ texk/tex4htk/t4ht.c
## prevent compiling Xdvi with libXp
sed -i~ 's|-lXp ||' texk/xdvik/configure
   
mkdir build
cd build

UB_CONFIGURE_DIR=../ ub_configure \
	--disable-native-texlive-build \
    --disable-multiplatform \
    --disable-xz \
    --disable-dump-share \
    --disable-aleph \
    --disable-bibtexu \
    --disable-dialog \
    --disable-psutils \
    --disable-t1utils \
    --enable-xindy \
    --disable-xindy-rules \
    --disable-xindy-docs \
    --enable-luatex \
	--with-banner-add=/UHU-Linux \
	--with-system-cairo \
	--with-system-freetype2 \
	--with-system-gd \
	--with-system-gmp \
	--with-system-graphite2 \
	--with-system-harfbuzz \
	--with-system-icu \
	--with-system-libpaper \
	--with-system-libpng \
	--with-system-mpfr \
	--with-system-pixman \
	--with-system-poppler \
	--with-system-zlib \
	--with-system-zziplib \
	--with-x \
    --with-clisp-runtime=default

ub_make

